export const brihtbraintallesblogData = [
  {
    id: 1,
    title: 'Apple and small steps',
    intro:
      'One day Jock decided to do something big. Very big. So big that he didn’t even know where to start.',
    body: [
      'He sat down and looked at the ceiling.',
      '— We have to start… but how?',
      'There was an apple lying nearby. An ordinary one. Jock took it and said:',
      '— Well, at least I’ll do something — I’ll eat an apple.',
      'He took a small bite. Then another. And another.',
      '— Hmm… I didn’t eat it all at once, — he thought. — I did it in parts.',
      'And then it dawned on him.',
      '— So that’s how big things work!',
      'He got up and took the first small step in his business. Then another. And another.',
      'And after a while everything didn’t seem so scary.',
      '— It turns out that big is just a lot of small things, — Jock smiled.',
    ],
    thought: 'If you don’t know where to start, start small.',
  },
  {
    id: 2,
    title: 'Banana and mood',
    intro: 'Jock woke up in a strange mood. Not bad, but not cheerful either.',
    body: [
      '— I’m kind of… like an unripe banana, — he said.',
      'And then he saw a banana on the table. One was yellow, the other was still a little green.',
      '— Oh, interesting.',
      'He took a green banana and tried it.',
      '— Well… not that.',
      'Then a yellow one.',
      '— Oh, that’s better!',
      'Jock sat down and thought:',
      '— Maybe it’s not the days, but the fact that everything takes time?',
      'He decided not to force anything. Just wait a little, relax a little.',
      'After a while, he was already laughing at some little things.',
      '— Oh, I’ve matured, — he said.',
    ],
    thought: 'The mood is also “ripening”. No need to put pressure on yourself.',
  },
  {
    id: 3,
    title: 'Orange and energy',
    intro: 'Jock decided to have a super productive day.',
    body: [
      '— Today I’ll do EVERYTHING! — he said.',
      'After 30 minutes, he was already lying on the couch.',
      '— Well… almost everything.',
      'An orange was lying nearby. He picked it up and started peeling it. Slowly.',
      '— It’s strange, — he said, — I’m not doing anything, and that’s better.',
      'He ate a piece. Then another.',
      'And suddenly he felt: energy was returning.',
      '— Maybe I shouldn’t do everything at once? — he thought.',
      'He did one small thing. Then a break. Then another.',
      'And the day went by.',
    ],
    thought:
      'Energy comes in waves. The main thing is not to try to do everything at once.',
  },
  {
    id: 4,
    title: 'Grapes and patience',
    intro: 'Jock wanted a quick result. Right now.',
    body: [
      '— Why can’t everything be done at once? — he grumbled.',
      'There were grapes on the table. He took one berry.',
      '— A small one, — he said.',
      'Ate it. Then another. And more.',
      'A minute later the bunch was gone.',
      '— Hmm… but I didn’t eat it all at once.',
      'He thought.',
      '— I just didn’t notice how it happened.',
      'And then he realized: some things happen gradually.',
      'He started doing his things the same way — a little at a time.',
      'And suddenly everything started moving.',
    ],
    thought: 'Patience is not waiting, but taking small steps regularly.',
  },
  {
    id: 5,
    title: 'Strawberries and attention',
    intro: 'Jock ate a strawberry and at the same time looked somewhere into the distance.',
    body: [
      '— Delicious… probably, — he said.',
      'He didn’t even realize that he had eaten half.',
      '— Wait… and what was it?',
      'He took another berry. He looked at it.',
      '— Small, red… interesting.',
      'He ate it slowly.',
      '— Oh! This is a completely different taste!',
      'Jock sat down and thought.',
      '— I didn’t even notice what I was doing.',
      'He began to pay attention to little things: how the tea sounded, how the light fell, how he breathed.',
      'And everything became more interesting.',
    ],
    thought: 'When you pay attention, even simple things become better.',
  },
];

