export const brihtbraintallesstoriesData = [
  {
    id: 1,
    title: 'Jock and a too serious day',
    intro:
      'One day Jock woke up and decided: — Today I will be as serious as possible.',
    body: [
      'He got up, made a very serious face and began to walk around the room as if he were solving important world affairs. Even when he saw his reflection, he did not smile. That was already suspicious.',
      'In the kitchen, he poured himself tea… and accidentally put a cookie in it. He did not dip it, but threw it straight in. And he stands there, watching.',
      '— This is an experiment, — he said very seriously.',
      'A minute later the cookie got soggy and fell apart. Jock looked into the cup… and could not stand it — he started laughing.',
      '— It seems that seriousness could not stand the first cookie, — he said.',
      'Then he went outside. There were children laughing, some running, some falling and getting up again. And then Jock understood: the world was not designed to be serious all the time.',
      'He raised his hands and said: — I officially declare: the serious day is canceled! And everyone around started laughing with him.',
    ],
    thought:
      'Sometimes the best solution is to simply allow yourself not to be perfect.',
  },
  {
    id: 2,
    title: 'Jock and the lost sock',
    intro: 'One morning Jock opened the drawer and found only one sock.',
    body: [
      'He froze.',
      '— This is already suspicious, — he said.',
      'He searched carefully. Under the bed. Inside the washing machine. Even checked places where socks clearly could not be.',
      '— A disappearance without witnesses, — he whispered.',
      'After a while he sat down, holding the one sock.',
      '— Maybe it left on its own, — he added thoughtfully.',
      'Jock slowly put it on and looked at his foot.',
      '— Well… this is a bold stylistic decision.',
      'He went outside like that. People walked by, busy with their own thoughts. No one noticed anything unusual.',
      'Jock looked around and then smiled.',
      '— It seems the world is not paying that much attention.',
    ],
    thought: 'Sometimes we worry about things nobody else even sees.',
  },
  {
    id: 3,
    title: 'Jock and the important list',
    intro: 'Jock decided that today required structure.',
    body: [
      'He took a notebook and carefully wrote at the top: — Important Things.',
      'Below, he listed: Be productive. Stay focused. Achieve results.',
      'He looked at the list for a long time, nodding.',
      '— This looks serious.',
      'Then he went to make tea.',
      'He came back and added: 4. Drink tea',
      'A few minutes later: 5. Sit for a moment',
      'Then: 6. Think about things',
      'Time passed. The list grew slowly, but none of the original items were touched.',
      'In the evening Jock looked at the page again.',
      '— I did not achieve results… but I definitely experienced the day.',
      'He closed the notebook.',
    ],
    thought: 'Not everything valuable can be checked off.',
  },
  {
    id: 4,
    title: 'Jock and the perfect plan',
    intro: 'Jock woke up early and decided: — Today everything will go according to plan.',
    body: [
      'He made a schedule down to the minute.',
      'At 09:00 — begin. At 09:05 — continue. At 09:10 — make progress',
      'He sat down exactly at 09:00.',
      'At 09:03 he noticed a bird outside the window.',
      'At 09:06 he was already watching how the light moved on the wall.',
      'At 09:12 he forgot what he was supposed to do.',
      'Jock looked at the paper.',
      '— The plan is still perfect, — he said.',
      'He folded it carefully and put it aside.',
      '— It is just that the day chose a different route.',
      'He stood up and followed it.',
    ],
    thought: 'Sometimes flexibility works better than perfection.',
  },
  {
    id: 5,
    title: 'Jock and the silent walk',
    intro:
      'Jock decided to go for a serious, silent walk. — No thoughts. No distractions, — he said.',
    body: [
      'He walked slowly, focusing on each step.',
      'After a minute he heard laughter somewhere nearby.',
      'He ignored it.',
      'Then a dog ran past him, tripped slightly, and kept running like nothing happened.',
      'Jock looked at it.',
      '— That was… unexpected.',
      'He continued walking.',
      'A cloud above him looked like something very strange.',
      '— Is that a dancing potato? — he whispered.',
      'He stopped, then smiled.',
      '— Silence is good… but life adds its own commentary.',
    ],
    thought: 'You do not have to silence the world to feel calm.',
  },
  {
    id: 6,
    title: 'Jock and the big decision',
    intro: 'Jock stood in the kitchen holding two apples.',
    body: [
      '— Today I will make a very thoughtful choice, — he said.',
      'He examined both carefully.',
      'One was slightly brighter. The other felt heavier.',
      'He turned them, compared them, even changed hands.',
      '— This one seems more… convincing.',
      'After a long pause, he chose one.',
      'Took a bite.',
      'Chewed slowly.',
      '— Yes… this tastes like apple.',
      'He looked at the second one.',
      '— I suspect the same outcome.',
      'Jock laughed quietly.',
    ],
    thought: 'Not every decision needs to be complicated.',
  },
  {
    id: 7,
    title: 'Jock and the serious mirror',
    intro: 'Jock stood in front of the mirror.',
    body: [
      '— Today I will remain completely serious.',
      'He straightened his posture and looked at himself.',
      'Very serious.',
      'One eyebrow moved slightly.',
      'He corrected it.',
      'Then the other eyebrow reacted.',
      'His face slowly turned into something strange.',
      '— This is not planned, — he said.',
      'He tried harder.',
      'The more serious he became, the more unusual his expression looked.',
      'After a few seconds, he could not hold it anymore.',
      'He started laughing.',
      '— It seems seriousness has limits.',
    ],
    thought: 'The harder you try to control everything, the more it slips.',
  },
  {
    id: 8,
    title: 'Jock and the empty moment',
    intro: 'Jock sat down on a chair.',
    body: [
      '— Now I will do nothing, — he said.',
      'He placed his hands on his knees and waited.',
      'At first, it felt strange.',
      'Too quiet. Too still.',
      'He looked around the room.',
      'Then listened to distant sounds.',
      'Then to his own breathing.',
      'Time passed slowly.',
      'Jock relaxed a little.',
      '— Maybe nothing is not empty, — he said quietly.',
      'He stayed there a bit longer.',
    ],
    thought: 'Doing nothing can still be something important.',
  },
  {
    id: 9,
    title: 'Jock and the unfinished thought',
    intro: 'Jock had a very important idea.',
    body: [
      '— I must remember this, — he said.',
      'He repeated it in his head and walked carefully across the room.',
      'Halfway there, the thought disappeared.',
      'He stopped.',
      '— That is unfortunate.',
      'Jock stood still, trying to catch it again.',
      'Nothing.',
      'He looked around, as if the thought might be somewhere nearby.',
      '— If it was truly important, it will return.',
      'He shrugged and continued walking.',
      'A few minutes later, he forgot that he even forgot something.',
    ],
    thought: 'Not everything needs to be held tightly to matter.',
  },
];
